#include "token.h"

const char *token_to_string(enum TokenType token) {
    switch (token) {
        // Single character tokens
        case TOKEN_APOS           : return "TOKEN_APOS";
        case TOKEN_COMMA          : return "TOKEN_COMMA";
        case TOKEN_DOT            : return "TOKEN_DOT";
        case TOKEN_DOUBLE_APOS    : return "TOKEN_DOUBLE_APOS";
        case TOKEN_LEFT_PAREN     : return "TOKEN_LEFT_PAREN";
        case TOKEN_MINUS          : return "TOKEN_MINUS";
        case TOKEN_PERCENT        : return "TOKEN_PERCENT";
        case TOKEN_PLUS           : return "TOKEN_PLUS";
        case TOKEN_RIGHT_PAREN    : return "TOKEN_RIGHT_PAREN";
        case TOKEN_SEMICOLON      : return "TOKEN_SEMICOLON";
        case TOKEN_SLASH          : return "TOKEN_SLASH";
        case TOKEN_STAR           : return "TOKEN_STAR";

        // One or two character tokens
        case TOKEN_BANG             : return "TOKEN_BANG";
        case TOKEN_BANG_EQUAL       : return "TOKEN_BANG_EQUAL";
        case TOKEN_EQUAL            : return "TOKEN_EQUAL";
        case TOKEN_GREATER          : return "TOKEN_GREATER";
        case TOKEN_GREATER_EQUAL    : return "TOKEN_GREATER_EQUAL";
        case TOKEN_LESS             : return "TOKEN_LESS";
        case TOKEN_LESS_EQUAL       : return "TOKEN_LESS_EQUAL";

        // Literals
        case TOKEN_IDENTIFIER:      return "TOKEN_IDENTIFIER";
        case TOKEN_NUMBER:          return "TOKEN_NUMBER";
        case TOKEN_STRING:          return "TOKEN_STRING";

        // Keywords
        case TOKEN_ABORT                : return "TOKEN_ABORT";
        case TOKEN_ACTION               : return "TOKEN_ACTION";
        case TOKEN_ADD                  : return "TOKEN_ADD";
        case TOKEN_AFTER                : return "TOKEN_AFTER";
        case TOKEN_ALL                  : return "TOKEN_ALL";
        case TOKEN_ALTER                : return "TOKEN_ALTER";
        case TOKEN_ALWAYS               : return "TOKEN_ALWAYS";
        case TOKEN_ANALYZE              : return "TOKEN_ANALYZE";
        case TOKEN_AND                  : return "TOKEN_AND";
        case TOKEN_AS                   : return "TOKEN_AS";
        case TOKEN_ASC                  : return "TOKEN_ASC";
        case TOKEN_ATTACH               : return "TOKEN_ATTACH";
        case TOKEN_AUTOINCREMENT        : return "TOKEN_AUTOINCREMENT";
        case TOKEN_BEFORE               : return "TOKEN_BEFORE";
        case TOKEN_BEGIN                : return "TOKEN_BEGIN";
        case TOKEN_BETWEEN              : return "TOKEN_BETWEEN";
        case TOKEN_BY                   : return "TOKEN_BY";
        case TOKEN_CASCADE              : return "TOKEN_CASCADE";
        case TOKEN_CASE                 : return "TOKEN_CASE";
        case TOKEN_CAST                 : return "TOKEN_CAST";
        case TOKEN_CHECK                : return "TOKEN_CHECK";
        case TOKEN_COLLATE              : return "TOKEN_COLLATE";
        case TOKEN_COLUMN               : return "TOKEN_COLUMN";
        case TOKEN_COMMIT               : return "TOKEN_COMMIT";
        case TOKEN_CONFLICT             : return "TOKEN_CONFLICT";
        case TOKEN_CONSTRAINT           : return "TOKEN_CONSTRAINT";
        case TOKEN_CREATE               : return "TOKEN_CREATE";
        case TOKEN_CROSS                : return "TOKEN_CROSS";
        case TOKEN_CURRENT              : return "TOKEN_CURRENT";
        case TOKEN_CURRENT_DATE         : return "TOKEN_CURRENT_DATE";
        case TOKEN_CURRENT_TIME         : return "TOKEN_CURRENT_TIME";
        case TOKEN_CURRENT_TIMESTAMP    : return "TOKEN_CURRENT_TIMESTAMP";
        case TOKEN_DATABASE             : return "TOKEN_DATABASE";
        case TOKEN_DEFAULT              : return "TOKEN_DEFAULT";
        case TOKEN_DEFERRABLE           : return "TOKEN_DEFERRABLE";
        case TOKEN_DEFERRED             : return "TOKEN_DEFERRED";
        case TOKEN_DELETE               : return "TOKEN_DELETE";
        case TOKEN_DESC                 : return "TOKEN_DESC";
        case TOKEN_DETACH               : return "TOKEN_DETACH";
        case TOKEN_DISTINCT             : return "TOKEN_DISTINCT";
        case TOKEN_DO                   : return "TOKEN_DO";
        case TOKEN_DROP                 : return "TOKEN_DROP";
        case TOKEN_EACH                 : return "TOKEN_EACH";
        case TOKEN_ELSE                 : return "TOKEN_ELSE";
        case TOKEN_END                  : return "TOKEN_END";
        case TOKEN_ESCAPE               : return "TOKEN_ESCAPE";
        case TOKEN_EXCEPT               : return "TOKEN_EXCEPT";
        case TOKEN_EXCLUDE              : return "TOKEN_EXCLUDE";
        case TOKEN_EXCLUSIVE            : return "TOKEN_EXCLUSIVE";
        case TOKEN_EXISTS               : return "TOKEN_EXISTS";
        case TOKEN_EXPLAIN              : return "TOKEN_EXPLAIN";
        case TOKEN_FAIL                 : return "TOKEN_FAIL";
        case TOKEN_FILTER               : return "TOKEN_FILTER";
        case TOKEN_FIRST                : return "TOKEN_FIRST";
        case TOKEN_FOLLOWING            : return "TOKEN_FOLLOWING";
        case TOKEN_FOR                  : return "TOKEN_FOR";
        case TOKEN_FOREIGN              : return "TOKEN_FOREIGN";
        case TOKEN_FROM                 : return "TOKEN_FROM";
        case TOKEN_FULL                 : return "TOKEN_FULL";
        case TOKEN_GENERATED            : return "TOKEN_GENERATED";
        case TOKEN_GLOB                 : return "TOKEN_GLOB";
        case TOKEN_GROUP                : return "TOKEN_GROUP";
        case TOKEN_GROUPS               : return "TOKEN_GROUPS";
        case TOKEN_HAVING               : return "TOKEN_HAVING";
        case TOKEN_IF                   : return "TOKEN_IF";
        case TOKEN_IGNORE               : return "TOKEN_IGNORE";
        case TOKEN_IMMEDIATE            : return "TOKEN_IMMEDIATE";
        case TOKEN_IN                   : return "TOKEN_IN";
        case TOKEN_INDEX                : return "TOKEN_INDEX";
        case TOKEN_INDEXED              : return "TOKEN_INDEXED";
        case TOKEN_INITIALLY            : return "TOKEN_INITIALLY";
        case TOKEN_INNER                : return "TOKEN_INNER";
        case TOKEN_INSERT               : return "TOKEN_INSERT";
        case TOKEN_INSTEAD              : return "TOKEN_INSTEAD";
        case TOKEN_INTERSECT            : return "TOKEN_INTERSECT";
        case TOKEN_INTO                 : return "TOKEN_INTO";
        case TOKEN_IS                   : return "TOKEN_IS";
        case TOKEN_ISNULL               : return "TOKEN_ISNULL";
        case TOKEN_JOIN                 : return "TOKEN_JOIN";
        case TOKEN_KEY                  : return "TOKEN_KEY";
        case TOKEN_LAST                 : return "TOKEN_LAST";
        case TOKEN_LEFT                 : return "TOKEN_LEFT";
        case TOKEN_LIKE                 : return "TOKEN_LIKE";
        case TOKEN_LIMIT                : return "TOKEN_LIMIT";
        case TOKEN_MATCH                : return "TOKEN_MATCH";
        case TOKEN_MATERIALIZED         : return "TOKEN_MATERIALIZED";
        case TOKEN_NATURAL              : return "TOKEN_NATURAL";
        case TOKEN_NO                   : return "TOKEN_NO";
        case TOKEN_NOT                  : return "TOKEN_NOT";
        case TOKEN_NOTHING              : return "TOKEN_NOTHING";
        case TOKEN_NOTNULL              : return "TOKEN_NOTNULL";
        case TOKEN_NULL                 : return "TOKEN_NULL";
        case TOKEN_NULLS                : return "TOKEN_NULLS";
        case TOKEN_OF                   : return "TOKEN_OF";
        case TOKEN_OFFSET               : return "TOKEN_OFFSET";
        case TOKEN_ON                   : return "TOKEN_ON";
        case TOKEN_OR                   : return "TOKEN_OR";
        case TOKEN_ORDER                : return "TOKEN_ORDER";
        case TOKEN_OTHERS               : return "TOKEN_OTHERS";
        case TOKEN_OUTER                : return "TOKEN_OUTER";
        case TOKEN_OVER                 : return "TOKEN_OVER";
        case TOKEN_PARTITION            : return "TOKEN_PARTITION";
        case TOKEN_PLAN                 : return "TOKEN_PLAN";
        case TOKEN_PRAGMA               : return "TOKEN_PRAGMA";
        case TOKEN_PRECEDING            : return "TOKEN_PRECEDING";
        case TOKEN_PRIMARY              : return "TOKEN_PRIMARY";
        case TOKEN_QUERY                : return "TOKEN_QUERY";
        case TOKEN_RAISE                : return "TOKEN_RAISE";
        case TOKEN_RANGE                : return "TOKEN_RANGE";
        case TOKEN_RECURSIVE            : return "TOKEN_RECURSIVE";
        case TOKEN_REFERENCES           : return "TOKEN_REFERENCES";
        case TOKEN_REGEXP               : return "TOKEN_REGEXP";
        case TOKEN_REINDEX              : return "TOKEN_REINDEX";
        case TOKEN_RELEASE              : return "TOKEN_RELEASE";
        case TOKEN_RENAME               : return "TOKEN_RENAME";
        case TOKEN_REPLACE              : return "TOKEN_REPLACE";
        case TOKEN_RESTRICT             : return "TOKEN_RESTRICT";
        case TOKEN_RETURNING            : return "TOKEN_RETURNING";
        case TOKEN_RIGHT                : return "TOKEN_RIGHT";
        case TOKEN_ROLLBACK             : return "TOKEN_ROLLBACK";
        case TOKEN_ROW                  : return "TOKEN_ROW";
        case TOKEN_ROWS                 : return "TOKEN_ROWS";
        case TOKEN_SAVEPOINT            : return "TOKEN_SAVEPOINT";
        case TOKEN_SELECT               : return "TOKEN_SELECT";
        case TOKEN_SET                  : return "TOKEN_SET";
        case TOKEN_TABLE                : return "TOKEN_TABLE";
        case TOKEN_TEMP                 : return "TOKEN_TEMP";
        case TOKEN_TEMPORARY            : return "TOKEN_TEMPORARY";
        case TOKEN_THEN                 : return "TOKEN_THEN";
        case TOKEN_TIES                 : return "TOKEN_TIES";
        case TOKEN_TO                   : return "TOKEN_TO";
        case TOKEN_TRANSACTION          : return "TOKEN_TRANSACTION";
        case TOKEN_TRIGGER              : return "TOKEN_TRIGGER";
        case TOKEN_UNBOUNDED            : return "TOKEN_UNBOUNDED";
        case TOKEN_UNION                : return "TOKEN_UNION";
        case TOKEN_UNIQUE               : return "TOKEN_UNIQUE";
        case TOKEN_UPDATE               : return "TOKEN_UPDATE";
        case TOKEN_USING                : return "TOKEN_USING";
        case TOKEN_VACUUM               : return "TOKEN_VACUUM";
        case TOKEN_VALUES               : return "TOKEN_VALUES";
        case TOKEN_VIEW                 : return "TOKEN_VIEW";
        case TOKEN_VIRTUAL              : return "TOKEN_VIRTUAL";
        case TOKEN_WHEN                 : return "TOKEN_WHEN";
        case TOKEN_WHERE                : return "TOKEN_WHERE";
        case TOKEN_WINDOW               : return "TOKEN_WINDOW";
        case TOKEN_WITH                 : return "TOKEN_WITH";
        case TOKEN_WITHOUT              : return "TOKEN_WITHOUT";

        // Parse
        case TOKEN_EOF:             return "TOKEN_EOF";
        case TOKEN_ERROR:           return "TOKEN_ERROR";

        default:                    return "UNDEFINED TOKEN";
    }
}